QRProject/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QRProject.Models;
using QRProject.Core;
using QRProject.helper;
using QRProject.zarinpal;
using System.IO;
using System.Text.RegularExpressions;
using QRProject.FactorViewModel;
using QRProject.meli;
using Newtonsoft.Json.Linq;
using System.Net;

namespace QRProject.Controllers
{

    //کنترلر مربوط به سبد خرید
    //تفاوتی که ما با سایر فروشگاه ها داریم این هست که ما مجموعه ای از فروشگاه ها رو در بر میگیریم پس به تعداد
    //فروشگاه ها سبد خرید باید داشته باشیم
    //نکته دوم:فروشگاه ها از دو صفحه کالا برای صفحه خرید مبفرستن
    //پرداکت که از صفحه اصلی یعنی شو و دوم از صفحه مور پروداکتشون
    public class ShopCartController : Controller
    {



        // GET: ShopCart

        //clientId hamun esme uniq furushgahe masalan "diamond" pas yek esme
        //liste sabade kharid ro neshun mide bar asase name furushgah ke hamun clientid hast , tashkhis mide
        //har furushgah yek session ba name khodesh baraye sabade kharid misaze
        //is lowprice baraye in hast ke hadeaghal mizan baraye furush ast va az samte pardakht miad
        //felan hard code hast va hade aghal 50 toman ast
        public ActionResult myindex(string ClientId, string tab, string CommonCode, string BackLinkFromMore, string IsLowPrice)
        {
            //agar mablaghe kharid hash az 50T kamtar bud bia tu view begu behe
            if (IsLowPrice=="yes")
            {
                ViewBag.isLowPrice = "حداقل مبلغ خرید 50 هزارتومان میباشد";

             }
            //agar az moreBiad Linkro Begir back ro ke zad bargarde daghighan hamun page o hamun search more:)
            ViewBag.BackLinkFromMore = BackLinkFromMore;

            //yani code eshterak ijad karde va az samte action SetCommonCode miad
            //CommonCode ro tu tabe dovvom ke marbute be ijade code eshterake va az unja kolan charkheye karesh shuru shode
            //bebar va code ro ham behesh begu
            if (tab == "Active" && CommonCode != null)
            {
                ViewBag.CommonCode = CommonCode;
            }

            if (tab == "EshterakNotFound" && CommonCode != null)
            {
                ViewBag.EshterakNotFound = CommonCode;
            }

            //in vase moghei gozashtam ke yeki tu ijad eshterak sheytanat kone va id ro pak kone
            //yeki in ghete code ro neveshtam yeki ham tu replace 
            //Tuye ghesmate returnClientTitle
            //hamun if dakhelesh
            //.........................................

            ApplicationDbContext db = new ApplicationDbContext();
            if (ClientId == null)
            {
                ClientId = db.Client.OrderByDescending(e => e.CreateDate).ToList().FirstOrDefault().Id;

            }


            ViewBag.Client = ClientId;
            List<ShopCartViewModel> list = new List<ShopCartViewModel>();

            //بیا ببین این فرد از این فروشگاه سبد خرید دارد
            if (Session[ClientId] != null)
            {
                //اگر دارد سشن را به لیست شاپکارت تبدیل کن
                //شاپکارت یک کلاس ،حداقل چیزهای مورد نیاز که حجم رم هم کم باشه
                //مورپروداکت یا پروداکت با تعداد
                List<ShopCartItem> cart = Session[ClientId] as List<ShopCartItem>;


                //ممکن سشن داشته باشه ولی تعداد محصولات  صفر باشه که ارور میده پس بیا چک کن
                if (cart.Count >= 1)
                {

                    //حالا برو داخل لیست و ببین سبد کالاش، چندتاش از پروداکت هست و چندتاش از مور پروداکت
                    foreach (var shopCartItem in cart)
                    {

                        //pas moreProduct ast
                        if (shopCartItem.ProductId == null)
                        {
                            //bia chek kon bebin furushande mahsul ro pak nakarde inke tu sabade kharide bude(albate hichvaght pak nemishe faghat az dide furushande makhfi mishe)
                            //inkar baraye amniat va dashtane madrak badan shayad lazem beshe
                            var moreProduct = db.MoreProducts.Where(w => w.MoreProductId == shopCartItem.MoreProductId && w.Display == null).FirstOrDefault();
                            //agar null nabud yani pas pak nakarde va hanuz tu database
                            if (moreProduct != null && moreProduct.count > 0)
                            {
                                list.Add(new ShopCartViewModel()
                                {
                                    ClientId = ClientId,
                                    MoreProductId = shopCartItem.MoreProductId,
                                    Count = shopCartItem.Count,
                                    Title = moreProduct.pTitle,
                                    Price = Convert.ToInt32(moreProduct.GheymatFeli),
                                    Sum = shopCartItem.Count * Convert.ToInt32(moreProduct.GheymatFeli),
                                    ImageAddress = moreProduct.pPicAddres

                                });
                            }

                        }

                        //pas Product ast
                        if (shopCartItem.MoreProductId == null)
                        {
                            //bia chek kon bebin furushande mahsul ro pak nakarde inke tu sabade kharide bude(albate hichvaght pak nemishe faghat az dide furushande makhfi mishe)
                            //inkar baraye amniat va dashtane madrak badan shayad lazem beshe
                            var Product = db.Product.Where(e => e.pId == shopCartItem.ProductId && e.Display == null).FirstOrDefault();
                            //agar null nabud yani pas pak nakarde va hanuz tu database
                            if (Product != null && Product.count > 0)
                            {
                                list.Add(new ShopCartViewModel()
                                {
                                    ClientId = ClientId,
                                    ProductId = shopCartItem.ProductId,
                                    Count = shopCartItem.Count,
                                    Title = Product.pTitle,
                                    Price = Convert.ToInt32(Product.GheymatFeli),
                                    Sum = shopCartItem.Count * Convert.ToInt32(Product.GheymatFeli),
                                    ImageAddress = Product.pPicAddres

                                });
                            }

                        }
                    }
                }
                //agar session mosavi nul bud ya sesseion dasht vali kalayi nabud
                //1-tedade mahsulatesh 0 sesseion ijad karde vali badan mahsoolatesh ro pak karde
                else
                {
                    //فرم اطلاعات فردی رو اصلا بهش نشون نده

                    ViewBag.NotSession = "NOT";
                }
            }
            //agar session mosavi nul bud ya sesseion dasht vali kalayi nabud
            //2-session nadare
            else
            {
                //اگر سشن نداشت فرم اطلاعات فردی رو اصلا بهش نشون نده
                ViewBag.NotSession = "NOT";
            }

            //agar list be har dalili(hala furushande pak karde mahsul ro ya ...)
            //baz ham namayesh nade forme etelaat ro
            if (list.Count == 0)
            {
                ViewBag.NotSession = "NOT";
            }
            return View(list);
        }




        //از سمت صفحه ویترین (شو و مور پروداکت) با ایجکس به این متد دسترسی پیدا میکنیم
        //سبد خرید را با توجه به اینکه پروداکت است و یا مورپروداکت است پر کن
        // نکته مهم این است که چون این پروژه شامل چند فروشگاه است سشن های مربوط به هر فروشگاه باید جدا ساخته شود
        //یعنی من از یک فروشگاه یک تعداد کالا داخل سبد خرید دارم و از یک فروشگاه دیگر یک تعداد دیگر
        //این ها باید جدا باشند به همین دلیل برای هر فروشگاه یک سشن جدا با نام فروشگاه بساز

        public ActionResult AddToCart(string ProductId, string MoreProductId, string ClientId)
        {
            List<ShopCartItem> cart = new List<ShopCartItem>();

            //اگر نال نبود یعنی این چندمین خریدش هست نه اولی
            if (Session[ClientId] != null)
            {
                //سشن را کست کن و پس بده
                cart = Session[ClientId] as List<ShopCartItem>;
            }


            //پس این محصول پروداکت است و توی پروداکت ها بگرد
            if (MoreProductId == null)
            {
                //حالا اگه از این محصول قبلا بوده یکی به تعدادش اضافه کن
                if (cart.Any(p => p.ProductId == ProductId))
                {
                    var findItem = cart.Where(r => r.ProductId == ProductId).FirstOrDefault();
                    ApplicationDbContext db = new ApplicationDbContext();
                    var myProduct = db.Product.Where(r => r.pId == ProductId && r.ClienId == ClientId).FirstOrDefault();
                    var SumAnbar = myProduct.count - findItem.Count;
                    if (SumAnbar > 0)
                    {
                        findItem.Count += 1;
                    }
                }
                //در غیر این صورت اولین بار داره این کالا رو میخره
                else
                {
                    cart.Add(new ShopCartItem()
                    {
                        ProductId = ProductId,
                        Count = 1

                    });
                }
            }

            //در غیر این صورت
            //پس این محصول مور پروداکت است و توی مور پروداکت ها دنبال آن بگرد
            if (ProductId == null)
            {
                //حالا اگه از این محصول قبلا بوده یکی به تعدادش اضافه کن
                if (cart.Any(p => p.MoreProductId == MoreProductId))
                {
                    var findItem2 = cart.Where(r => r.MoreProductId == MoreProductId).FirstOrDefault();
                    ApplicationDbContext db = new ApplicationDbContext();

QRProject/Views/ShopCart/GoPay.cshtml
@{
    Layout = null;
}




<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>خطای پرداخت</title>

    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="~/errorPage/css/style.css" />
    <style>
        .button {
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }



        .button2 {
            background-color: white;
            color: black;
            border: 2px solid #008CBA;
        }

            .button2:hover {
                background-color: #008CBA;
                color: white;
            }
    </style>

</head>
<body>

    <div id="notfound">
        <div style="direction:rtl" class="notfound">

            <div class="notfound-404 "></div>
            <h3>baladchee.com</h3>
            <div style="font-size:30px;font-weight:bold" class="translate">خطای پرداخت</div>
            <h3>تراکنش با شکست مواجه شد!</h3>
            <p style="width:310px">@ViewBag.error</p>

            <a class="button button2" href="@Url.Action("myindex","ShopCart",new {ClientId= ViewBag.clientid })">بازگشت</a>
        </div>
    </div>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="e4b4b090a7c0c9729d3f17af-text/javascript"></script>



    <script type="e4b4b090a7c0c9729d3f17af-text/javascript">
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
</body>
</html>

QRProject/Views/ShopCart/Verify.cshtml
@{
    Layout = null;
}




@if (ViewBag.isSuccess == true)
{


    <!DOCTYPE html>
    <html lang="en">


    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>پرداخت موفق</title>

        <link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

        <link type="text/css" rel="stylesheet" href="~/errorPage/css/style.css" />
        <style>
            body{
                 background-color:rgb(255,245,231);
             
            }
            .button {
                background-color: #4CAF50; /* Green */
                border: none;
                color: white;
                padding: 16px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                transition-duration: 0.4s;
                cursor: pointer;
            }



            .button2 {
                background-color: white;
                color: black;
                border: 2px solid #008CBA;
            }

                .button2:hover {
                    background-color: #008CBA;
                    color: white;
            }
        </style>

    </head>
    <body>

        <div id="notfound">
            <div style="direction:rtl" class="notfound">

                <div class="notfound-404 "></div>

                <div style="font-size:30px;font-weight:bold" class="translate">baladchee.com</div>
                <h3>پرداخت موفقیت آمیز بود</h3>
                <p style="width:310px">کد پیگیری شما : @ViewBag.refId</p>
                <br />
                <img src="~/images/SellerGif.gif" alt="SmsShape" />
                <div>خرید شما از طریق پیامک به فروشنده اطلاع داده شد.</div>
                               
                <a class="button button2" href="@Url.Action("show","Home",new {id= ViewBag.clientid })">بازگشت به صفحه  @ViewBag.clientid</a>
            
                <a class="button button2" href="@Url.Action("pdf","shopcart",new {FactorId= ViewBag.factorId})">دریافت فاکتور  PDF</a>

            </div>
        </div>

        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="e4b4b090a7c0c9729d3f17af-text/javascript"></script>



        <script type="e4b4b090a7c0c9729d3f17af-text/javascript">
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');
        </script>
    </body>

</html>






}
else
{



    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>خطای پرداخت</title>

        <link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

        <link type="text/css" rel="stylesheet" href="~/errorPage/css/style.css" />
        <style>

                   body{
                background-color:rgb(255,245,231);
            }
            .button {
                background-color: #4CAF50; /* Green */
                border: none;
                color: white;
                padding: 16px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                transition-duration: 0.4s;
                cursor: pointer;
            }



            .button2 {
                background-color: white;
                color: black;
                border: 2px solid #008CBA;
            }

                .button2:hover {
                    background-color: #008CBA;
                    color: white;
                }
        </style>

    </head>
    <body>

        <div id="notfound">
            <div style="direction:rtl" class="notfound">

                <div class="notfound-404 "></div>
                <h3>baladchee.com</h3>
                <div style="font-size:30px;font-weight:bold" class="translate">خطای پرداخت</div>
                <h3>تراکنش با شکست مواجه شد!</h3>
                <p style="width:310px">در صورت کسر مبلغ از حساب شما، طی ۲۴ ساعت آینده مبلغ بازگردانده خواهد شد.</p>
                @*کد تراکنش ناموفق شما : @ViewBag.Status*@
       

                <a class="button button2" href="@Url.Action("show","Home",new {id= ViewBag.clientid })">بازگشت به صفحه  @ViewBag.clientid</a>
          
              </div>
        </div>

        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="e4b4b090a7c0c9729d3f17af-text/javascript"></script>



        <script type="e4b4b090a7c0c9729d3f17af-text/javascript">
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');
        </script>
    </body>
</html>


}